### PR TITLE
Correct regex for package name

### PR DESCRIPTION
**Pull request by KevCaz**
- fix the issue described in #61.
- fix a typo.

### CODE REVIEW

**Comment by jimhester** [comment]
Can you please add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by KevCaz** [comment]
Sure.

**Comment by KevCaz** [comment]
done.

**Comment by jimhester** [comment]
Thanks a bunch!

**Comment by KevCaz** [comment]
Thanks @jimhester for your efforts on all the great packages you are maintaining.

**Pull request merged**
